# Generated by Django 4.1.5 on 2023-01-27 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0003_mensaje_delete_mensajes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='user',
        ),
    ]
