# Generated by Django 4.1.5 on 2023-01-27 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0004_remove_mensaje_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='user',
        ),
    ]
