# Generated by Django 4.1.5 on 2023-02-09 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mensajeria', '0009_e_delete_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='Msjs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receptor', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('leido', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='e',
        ),
        migrations.DeleteModel(
            name='Msj',
        ),
    ]
