# Generated by Django 4.1.5 on 2023-02-09 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mensajeria', '0012_url_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='descripcion',
        ),
    ]
