# Generated by Django 4.1.5 on 2023-01-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_blog_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(upload_to='imagenes'),
        ),
    ]
