# Generated by Django 4.1.5 on 2023-01-26 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_perfil_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
