# Generated by Django 4.1.5 on 2023-02-09 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_blog_cuerpo_alter_blog_fecha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
